# Generated by Django 5.2.17 on 2026-09-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default='public', max_length=200),
        ),
    ]
